### ISSUE TITLE
Playlists reloading takes a long time

### ISSUE THREAD

**Issue by bigmittens** [dirkgroenen/mopidy-mopify#29]
playlists are loaded each time when clicked. loading larger playlists take a long time, it seems a lot quicker on other web UIs.

**Comment by dirkgroenen** [comment]
Can you be a bit more specific about your setup? Which version are you using and are you running it on a normal computer or for example a Raspberry?

**Comment by bigmittens** [comment]
Normal computer, running Arch on x86_64.

**Comment by bigmittens** [comment]
I could have described the issue a little better too, sorry. When I load the playlist (about ~400 songs) it will load the first 20 or so songs normally, then when I start to scroll down it will lock up for a second or too and load the next 20 songs and so forth. On moped or musicbox all of the songs load at once.

**Comment by dirkgroenen** [comment]
Ah, that changes the problem. I've implemented that "feature" to prevent a slower browser from hanging. While developing Firefox had a bad habit of freezing when loading more than +/- 500 songs, so to prevent this freeze Mopify adds the tracks in batches. 

I can try to improve the speed of this process.

**Comment by bigmittens** [comment]
Can this be reopened? The problem still occurs for me. Could an option maybe be added to load playlists in batches or not?

**Comment by dirkgroenen** [comment]
The tracks are added to the screen when scrolling. This should prevent the browser from freezing. I'm afraid the performance will drop even further when loading all tracks at one.

**Comment by bigmittens** [comment]
How long would it take if you were to set them to load all at once? Here is also a [video](http://a.pomf.se/sdocya.webm) of the issue.

**Comment by dirkgroenen** [comment]
All the tracks are already loaded, but not all shown. When you scroll down the tracks are added to the list in batches and that's what creates the freeze. 

To be honest, I don't know how to fix this without showing all tracks from the start. Maybe some improvement in the directives or something like that could help... I'll do some searching in the hope to find something useful.

**Comment by artistro08** [comment]
I'm testing this running on a Raspberry Pi 2 and it hangs in all browsers. It works for a bit. then every so often it freezes even if I don't scroll. using Google Chrome on elementaryOS and Android.

**Comment by dirkgroenen** [comment]
Mopify is quite a heave client with around 175MB RAM while on idle. I haven't tested it in a browser on a Raspberry PI, but I can imagine that it drains a lot of the PI's power. 

I must admit that my focus with this project isn't to create a client that can run on every browser and (low-end) computer, though I would like to help if things are easy to solve. If you create your own Issue and explain all the problems you encounter when running on a Raspberry I'll might be able to help you. Don't forget to add some extra details like ```top```'s output and so on.

**Comment by artistro08** [comment]
Will Do!

**Comment by dirkgroenen** [comment]
Fixed in 1.3.1 which I've just released. I've tested it with a playlist containing 2000 tracks and everything went well.

**Comment by artistro08** [comment]
now the only problem I have with it is that it doesn't load the tracks on large playlists

**Comment by dirkgroenen** [comment]
Could it also be that your Raspberry just hangs when loading the big tracklist? My experience with the Raspberry is that it has quite some issues when it comes to loading big tracklists/playlists.

**Comment by artistro08** [comment]
Well, Since I got the RPi 2 it hasn't hanged on much at all. When I double click it, it does try and add the songs. but no dice

**Comment by dirkgroenen** [comment]
Sorry, haven't read that you're using a Raspberry 2. Can you check your console for errors and place them here?

**Comment by artistro08** [comment]
Yes, I'll post in a little e

**Comment by artistro08** [comment]
Bit*
